CC=gcc
CFLAGS=-Wall -Wextra -Werror
MAIN= ft_isascii.c ft_memcmp.c ft_strchr.c \
	  ft_strrchr.c ft_bzero.c ft_isdigit.c \
	  ft_memcpy.c ft_strdup.c ft_tolower.c \
	  ft_isalnum.c ft_isprint.c ft_memmove.c \
	  ft_strlen.c ft_toupper.c ft_isalpha.c \
	  ft_memchr.c ft_memset.c ft_strncmp.c \
	  test.c

NAME:

all:

clean:

fclean:

re:
